name: garmin_client
description: Dart library for exporting data from Garmin Connect
version: 1.0.5
author: Marcus Johansson <majohansson@gmail.com>
homepage: https://github.com/marcjoha/garmin_client

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  dio: ^2.1.13
  cookie_jar: ^1.0.0
  dio_retry: ^0.1.8-beta

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
