name: garmin_client
description: Dart library for exporting data from Garmin Connect
version: 1.0.6
author: Marcus Johansson <majohansson@gmail.com>
homepage: https://github.com/marcjoha/garmin_client

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  dio: 3.0.10
  dio_cookie_manager: ^1.0.0
  dio_retry: 0.1.9-beta

dev_dependencies:
  pedantic: 1.0.0
  test: 1.0.0
